### ISSUE TITLE
What are we actually going to build

### ISSUE THREAD

**Issue by BrianSpencerDev** [Journey-Into-Javascript/clerk-hashnode-hackathon-app#1]
So far the ideas have been:

- small social media app
- music playlist sharing app

feel free to brainstorm and add more ideas or voice your liking of any of the current ideas

**Comment by BrianSpencerDev** [comment]
@anirban-s 
@NoelCov 

Any Ideas?

**Comment by NoelCov** [comment]
Nope I just woke up let me to some stuff and in like an hour I’ll sit down
and stay thinking of what we can make

**Comment by madCakes** [comment]
I'm pretty bad at coming up with ideas (It's Jason from the discord *wave*)

**Comment by BrianSpencerDev** [comment]
It's requirements are pretty relaxed. The only real requirement seems to be the use of clerk for auth. What would be some fun things that require a user sign in? 🤔

[Hackathon Article](https://townhall.hashnode.com/a-new-hackathon-the-clerk-and-hashnode-hackathon)

**Comment by NoelCov** [comment]
I’d say any app that gives you personal information so that people don’t
get weird about creating an account  haha

**Comment by BrianSpencerDev** [comment]
What do you mean?

**Comment by madCakes** [comment]
I like a lot of structure but don't want to bring down the mood over-managing things. But I think it would be good if we say by the end of the week we'll decide what we want to build and if not just choose a random one? just a suggestion, I have no real idea how these things work

**Comment by NoelCov** [comment]
Yes me too , I structure everything in my life lol. I’ve been just a bit
busy this morning but I’ll for sure think of something that we can work on.

**Comment by NoelCov** [comment]
How about we build a social media app? But only for developers? Where people could idk create an account and look for people to work on a project with them and then they would create like a group-chat within the app with those people? I just had that idea, pretty generic I know :/

**Comment by BrianSpencerDev** [comment]
When I code I listen to music. People always talk about their go to playlists when working. So we could combine the ideas mentioned and we could we make a very barebones social media app where people share their playlists/songs they code to. We could make it reddit style where people upvote/downvote and your feed is ranked by votes and you get to see the "hottest" playlists

And if we nail the basics we can expand upon it and people choose categories for the playlist(not just coding): studying, working out, traffic commute, and etc etc 

**or**

if we don't want to go the social media app we can just do a music player of sorts that players the music you have across different platforms because its annoy to jump from lets say spotify to soundcloud to youtube 🤷🤷🤷

**Comment by anirban-s** [comment]
The projects will be evaluated based on the following criteria:

**Product Thinking**: Usefulness of the project be in a real-world scenario. Completeness of the features implemented.
**UI/UX**: The overall look, layout, color usage, and positioning in the application.
**Code**: Quality(clean code, proper naming conventions linters usage) of code, and use of best practices.
**Completeness of the article**: The blog should cover all aspects of your project. What inspired you to create this project, the problem the project is targeting, and how you made it.
**Comprehensibility**: Try to avoid intricate language jargon in your blog. Use simple language to convey your thoughts.

So, these are the evaluation criteria I found. So, when we finalize the topic someone should start writting the blog. 

I point of view is to pick a simple but useful product and start working on it. Do we know the deadline?

**Comment by BrianSpencerDev** [comment]
July 30th, 2021 (23:59 PT): Hackathon’s deadline for submission

We will also make Friday our design deadline. So we should have settled on an idea and at least a rough ui "sketch" by then

**Comment by fawazsullia** [comment]
Idea: An affiliate platform where creators can list their products ( books, courses ) and influencers can promote them for commissions

**Comment by BrianSpencerDev** [comment]
If there isn't any idea that people agree to do I believe it would be good to default to the playlist sharing app by the end of tomorrow in order to keep things moving along.

**Comment by NoelCov** [comment]
Yes I agree I think the playlist sharing website is a really good idea. uhm I've done some of my designes in figma but I'm not an expert in it. Who should start it?

**Comment by anirban-s** [comment]
I agree with the playlist sharing website. I not good with design so if anyone can make any kind of design I am happy with it and willing to work on that. Also I can start looking into the Clark API and the backend stuff.

**Comment by BrianSpencerDev** [comment]
Alright we will build a playlist sharing app. 

As far as design goes feel free to get some sketches or some simple figma designs done. Doesn't have to be one person but If you're up to the task @NoelCov go for it.  I'll try my hand at some rough designs. On Friday we can come together and compare.

 It is also a good idea at this point to skim/read through the [Clerk Docs](https://docs.clerk.dev/) if you haven't already.
