### ISSUE TITLE
Tech Stack to Be Used?

### ISSUE THREAD

**Issue by BrianSpencerDev** [Journey-Into-Javascript/clerk-hashnode-hackathon-app#2]
I'm comfortable with 

- html
- css/scss/tailwind
- javascript/nodejs
- react
- next.js
- mongoDB

**Comment by anirban-s** [comment]
I am comfortable with: 

- html
- css/bootstrap
- javascript/nodejs
- angular/ (basics of react)
- mongoDB/mySQL
- C# .net
- python

I think we should pick javascript stack as these are common among us.

**Comment by madCakes** [comment]
I am comfortable with:

- html
- css (weak but know it)
- javascript

Currently learning React

**Comment by BrianSpencerDev** [comment]
Would you guys be comfortable working in react?

If not we could always use express and node.js

**Comment by madCakes** [comment]
I'm happy to, I am very new to it but doesn't feel like its too out of my depth.

**Comment by BrianSpencerDev** [comment]
Okay if there are no objections then the project will be done in react (create-react-app)

**Comment by BrianSpencerDev** [comment]
Alright we will use react for the front end and nodejs for the backend
