### ISSUE TITLE
Sass or CSS Frameworks?

### ISSUE THREAD

**Issue by BrianSpencerDev** [Journey-Into-Javascript/clerk-hashnode-hackathon-app#8]
What would everyone like the project to use css-wise?

Options:
- plain css
- scss
- TailwindCSS

**Comment by madCakes** [comment]
I've not really touched anything but css, although I'm a fast learner.

**Comment by BrianSpencerDev** [comment]
We will do scss then since it's not that much different than css but gives a lot of more functionality for us the developers.
